version: '3.4'

services:
  app:
    container_name: joe-java
    image: joe-java
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80

# Start: docker-compose up -d --build
# Stop: docker-compose down --rmi all